FROM openjdk:17-jdk-slim

WORKDIR /app

COPY h2-2.3.232.jar /app/h2.jar

EXPOSE 9092 8082

CMD ["java", "-cp", "/app/h2.jar", "org.h2.tools.Server", "-tcp", "-tcpPort", "9092", "-tcpAllowOthers", "-web", "-webAllowOthers", "-ifNotExists"]
